name: Count Issues

on:
  schedule:
    # At 13:00 (1 pm) UTC / 8:00 EST on Monday
    - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:
  count_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Count Incident Action issues
      uses: kazupon/issue-count-action@284ff91974f64c6ac7192a394d895434eabee85f
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: 
          -'Bug | Bogue'
          -'Incident Action'
          -'Tech Debt'
        state: open